services:
  # Backend API Service
  - type: web
    name: hipaa-guard-ai-backend
    env: node
    plan: free
    buildCommand: cd backend && npm install
    startCommand: cd backend && npm start
    healthCheckPath: /api/health
    autoDeploy: true
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5000

  # Frontend Static Site
  - type: web
    name: hipaa-guard-ai-frontend
    env: static
    buildCommand: cd frontend && npm install && npm run build
    staticPublishPath: frontend/build
    autoDeploy: true

databases:
  - name: hipaa-guard-ai-database
    databaseName: hipaa_guard_ai
    user: hipaa_user
    plan: free
